#!/usr/bin/perl -l
#
# Ferm deluser script
# Rootnode, http://rootnode.net
#
# Copyright (C) 2012 Marcin Hlybin
# All rights reserved.
#
# The script creates ferm configuration

use warnings;
use strict;
use Readonly;

# Configuration
Readonly my $LXC_DIR  => '/lxc/user';
Readonly my $FERM_DIR => '/etc/ferm/ferm.d'; 

# Check paths
-d $LXC_DIR  or die "\$LXC_DIR ($LXC_DIR) not found.\n";
-d $FERM_DIR or die "\$FERM_DIR ($FERM_DIR) not found.\n";

# Get arguments
die "Uneven number of arguments." if @ARGV % 2;
my %arg = @ARGV;

# Mandatory arguments
my $uid         = $arg{uid}         or die "Uid not specified.";
my $user_name   = $arg{user_name}   or die "User name not specified.";
my $server_no   = $arg{server_no}   or die "Server number not specified.";
my $server_type = $arg{server_type} or die "Server type not specified."; 
my $ipaddr      = $arg{ipaddr}      or die "IP address not specified.";

# Remove firewall rules file
my $ferm_file = "$FERM_DIR/$uid";
if (-f $ferm_file) {
	unlink $ferm_file or die "Cannot remove ferm file '$ferm_file'.";
	system("/etc/init.d/ferm restart");
}

exit;
