#!/usr/bin/perl -l
#
# Satan deluser script
# Rootnode, http://rootnode.net
#
# Copyright (C) 2012 Marcin Hlybin
# All rights reserved.
#
# The script configures satan

use warnings;
use strict;
use File::Path qw(remove_tree);
use Readonly;

# Configuration
Readonly my $TEMPLATE_DIR => '/lxc/template/user/rootfs/home/etc';
Readonly my $LXC_DIR      => '/lxc/user';

# Check paths
-d $TEMPLATE_DIR or die "\$TEMPLATE_DIR ($TEMPLATE_DIR) not found.\n";
-d $LXC_DIR      or die "\$LXC_DIR ($LXC_DIR) not found.\n";

# Get arguments
die "Uneven number of arguments." if @ARGV % 2;
my %arg = @ARGV;

# Mandatory arguments
my $uid         = $arg{uid}         or die "Uid not specified.";
my $user_name   = $arg{user_name}   or die "User name not specified.";
#my $server_no   = $arg{server_no}   or die "Server number not specified.";
#my $server_type = $arg{server_type} or die "Server type not specified."; 
#my $satan_key   = $arg{satan_key}   or die "Satan key not specified.";

## Satan proxy
# Remove service directory
my $proxy_service_dir = "/lxc/system/proxy/rootfs/etc/service/$uid";
if (-d $proxy_service_dir) {
	# Stop service
	system("/usr/bin/svc -d $proxy_service_dir");

	# Remove directory
	remove_tree($proxy_service_dir) or die "Cannot delete proxy service directory '$proxy_service_dir'";

	# Kill supervise process
	system("/usr/bin/pkill -f '^supervise $uid\$'");
}
exit;
